#	Copyright 2015-2016, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# [START runtime]
runtime: nodejs
vm: true
# [END runtime]
beta_settings:
      cloud_sql_instances: "visafinder-1346:us-central1:databasevisaid"

# [START env]
env_variables:
  # Replace user, password, and host with the values obtained when
  # configuring your Cloud SQL instance.
  MYSQL_HOST: 107.178.220.226
  MYSQL_USER: root
  MYSQL_PASSWORD: myang33
  MYSQL_DATABASE: visafinder
# [END env]
# [END app_yaml]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
