CREATE TABLE Destination
(
dID INT NOT NULL AUTO_INCREMENT,
Country VARCHAR(100),
PRIMARY KEY (dID)
);
CREATE TABLE Passport
(
	pID INT NOT NULL AUTO_INCREMENT,
	Country VARCHAR(100),
	PRIMARY KEY (pID)
);
CREATE TABLE RequireDocs
(
	ID INT NOT NULL AUTO_INCREMENT,
	DestId INT,
	PassId INT,
	Requred_Doc VARCHAR(800),
	PRIMARY KEY (ID),
	FOREIGN KEY (DestId) REFERENCES Destination(dID),
	FOREIGN KEY (PassId) REFERENCES Passport(pID)
);




