angular.module('ngTableApp', ['ngTable'])
        .controller('tableController', function ($scope, $filter, ngTableParams) {
        	$scope.users =
			        [{
						  "id": 1,
						  "first_name": "Peter",
						  "last_name": "White",
						  "email": "pwhite0@exblog.jp",
						  "country": "Netherlands",
						  "ip_address": "19.82.151.215"
						}, {
						  "id": 2,
						  "first_name": "Christopher",
						  "last_name": "Foster",
						  "email": "cfoster1@bloglovin.com",
						  "country": "China",
						  "ip_address": "164.5.67.81"
						}, {
						  "id": 3,
						  "first_name": "Joyce",
						  "last_name": "Moreno",
						  "email": "jmoreno2@nymag.com",
						  "country": "Norway",
						  "ip_address": "159.40.14.9"
						}, {
						  "id": 4,
						  "first_name": "Catherine",
						  "last_name": "Morales",
						  "email": "cmorales3@vimeo.com",
						  "country": "Costa Rica",
						  "ip_address": "155.238.167.52"
						}, {
						  "id": 5,
						  "first_name": "Lawrence",
						  "last_name": "Rose",
						  "email": "lrose4@youtu.be",
						  "country": "United States",
						  "ip_address": "123.113.85.211"
						}, {
						  "id": 6,
						  "first_name": "Emily",
						  "last_name": "Patterson",
						  "email": "epatterson5@engadget.com",
						  "country": "China",
						  "ip_address": "111.182.46.160"
						}, {
						  "id": 7,
						  "first_name": "Dennis",
						  "last_name": "Oliver",
						  "email": "doliver6@chronoengine.com",
						  "country": "China",
						  "ip_address": "6.214.27.28"
						}, {
						  "id": 8,
						  "first_name": "Andrea",
						  "last_name": "Ferguson",
						  "email": "aferguson7@amazon.co.uk",
						  "country": "United States",
						  "ip_address": "47.88.187.213"
						}, {
						  "id": 9,
						  "first_name": "Michael",
						  "last_name": "Woods",
						  "email": "mwoods8@phoca.cz",
						  "country": "Canada",
						  "ip_address": "93.141.90.24"
						}, {
						  "id": 10,
						  "first_name": "Maria",
						  "last_name": "Sullivan",
						  "email": "msullivan9@google.com.hk",
						  "country": "China",
						  "ip_address": "139.140.140.158"
						}, {
						  "id": 11,
						  "first_name": "John",
						  "last_name": "Flores",
						  "email": "jfloresa@sohu.com",
						  "country": "Russia",
						  "ip_address": "199.214.134.195"
						}, {
						  "id": 12,
						  "first_name": "William",
						  "last_name": "Sanchez",
						  "email": "wsanchezb@addtoany.com",
						  "country": "Philippines",
						  "ip_address": "122.36.23.95"
						}, {
						  "id": 13,
						  "first_name": "Nancy",
						  "last_name": "Bryant",
						  "email": "nbryantc@foxnews.com",
						  "country": "Sweden",
						  "ip_address": "3.201.73.157"
						}, {
						  "id": 14,
						  "first_name": "Adam",
						  "last_name": "Moreno",
						  "email": "amorenod@rakuten.co.jp",
						  "country": "Paraguay",
						  "ip_address": "152.31.85.241"
						}, {
						  "id": 15,
						  "first_name": "Kenneth",
						  "last_name": "Ortiz",
						  "email": "kortize@loc.gov",
						  "country": "Belarus",
						  "ip_address": "162.149.48.60"
						}, {
						  "id": 16,
						  "first_name": "Kevin",
						  "last_name": "Campbell",
						  "email": "kcampbellf@usnews.com",
						  "country": "Russia",
						  "ip_address": "219.60.52.203"
						}, {
						  "id": 17,
						  "first_name": "Emily",
						  "last_name": "Boyd",
						  "email": "eboydg@smh.com.au",
						  "country": "Bosnia and Herzegovina",
						  "ip_address": "211.219.189.225"
						}, {
						  "id": 18,
						  "first_name": "Mark",
						  "last_name": "Fox",
						  "email": "mfoxh@sfgate.com",
						  "country": "Indonesia",
						  "ip_address": "212.66.251.0"
						}, {
						  "id": 19,
						  "first_name": "Douglas",
						  "last_name": "Lane",
						  "email": "dlanei@plala.or.jp",
						  "country": "France",
						  "ip_address": "115.228.213.182"
						}, {
						  "id": 20,
						  "first_name": "Jeremy",
						  "last_name": "Nelson",
						  "email": "jnelsonj@wordpress.org",
						  "country": "Israel",
						  "ip_address": "142.198.55.159"
						}, {
						  "id": 21,
						  "first_name": "Tammy",
						  "last_name": "Roberts",
						  "email": "trobertsk@howstuffworks.com",
						  "country": "Paraguay",
						  "ip_address": "206.66.92.52"
						}, {
						  "id": 22,
						  "first_name": "Martha",
						  "last_name": "Ferguson",
						  "email": "mfergusonl@ifeng.com",
						  "country": "Benin",
						  "ip_address": "83.30.32.97"
						}, {
						  "id": 23,
						  "first_name": "Anna",
						  "last_name": "Owens",
						  "email": "aowensm@cbc.ca",
						  "country": "Italy",
						  "ip_address": "49.196.228.17"
						}, {
						  "id": 24,
						  "first_name": "Louise",
						  "last_name": "Young",
						  "email": "lyoungn@surveymonkey.com",
						  "country": "Russia",
						  "ip_address": "10.91.73.17"
						}, {
						  "id": 25,
						  "first_name": "Martha",
						  "last_name": "Riley",
						  "email": "mrileyo@nifty.com",
						  "country": "Sweden",
						  "ip_address": "5.40.93.92"
						}, {
						  "id": 26,
						  "first_name": "Bonnie",
						  "last_name": "Matthews",
						  "email": "bmatthewsp@businesswire.com",
						  "country": "Ukraine",
						  "ip_address": "161.49.148.112"
						}, {
						  "id": 27,
						  "first_name": "Frances",
						  "last_name": "Hunt",
						  "email": "fhuntq@biblegateway.com",
						  "country": "China",
						  "ip_address": "72.86.233.206"
						}, {
						  "id": 28,
						  "first_name": "Arthur",
						  "last_name": "Bell",
						  "email": "abellr@examiner.com",
						  "country": "Japan",
						  "ip_address": "55.172.216.236"
						}, {
						  "id": 29,
						  "first_name": "Catherine",
						  "last_name": "Lawson",
						  "email": "clawsons@google.it",
						  "country": "Macedonia",
						  "ip_address": "166.150.92.74"
						}, {
						  "id": 30,
						  "first_name": "Philip",
						  "last_name": "Meyer",
						  "email": "pmeyert@fema.gov",
						  "country": "Argentina",
						  "ip_address": "192.212.248.66"
						}, {
						  "id": 31,
						  "first_name": "Bobby",
						  "last_name": "Reid",
						  "email": "breidu@bizjournals.com",
						  "country": "Philippines",
						  "ip_address": "12.134.105.148"
						}, {
						  "id": 32,
						  "first_name": "Teresa",
						  "last_name": "Romero",
						  "email": "tromerov@mapy.cz",
						  "country": "Thailand",
						  "ip_address": "228.56.149.232"
						}, {
						  "id": 33,
						  "first_name": "Todd",
						  "last_name": "Bryant",
						  "email": "tbryantw@bbc.co.uk",
						  "country": "United States",
						  "ip_address": "246.196.136.251"
						}, {
						  "id": 34,
						  "first_name": "Sandra",
						  "last_name": "Carr",
						  "email": "scarrx@skype.com",
						  "country": "Indonesia",
						  "ip_address": "61.120.254.78"
						}, {
						  "id": 35,
						  "first_name": "Judith",
						  "last_name": "Watson",
						  "email": "jwatsony@state.tx.us",
						  "country": "Russia",
						  "ip_address": "214.77.201.132"
						}, {
						  "id": 36,
						  "first_name": "Joyce",
						  "last_name": "Payne",
						  "email": "jpaynez@loc.gov",
						  "country": "South Korea",
						  "ip_address": "206.3.145.53"
						}, {
						  "id": 37,
						  "first_name": "Carl",
						  "last_name": "Carter",
						  "email": "ccarter10@list-manage.com",
						  "country": "Philippines",
						  "ip_address": "180.183.245.43"
						}, {
						  "id": 38,
						  "first_name": "Ashley",
						  "last_name": "Hill",
						  "email": "ahill11@wired.com",
						  "country": "China",
						  "ip_address": "113.193.251.131"
						}, {
						  "id": 39,
						  "first_name": "Julia",
						  "last_name": "Arnold",
						  "email": "jarnold12@deviantart.com",
						  "country": "Indonesia",
						  "ip_address": "193.74.105.101"
						}, {
						  "id": 40,
						  "first_name": "Aaron",
						  "last_name": "Willis",
						  "email": "awillis13@weibo.com",
						  "country": "Japan",
						  "ip_address": "21.253.181.39"
						}, {
						  "id": 41,
						  "first_name": "Brandon",
						  "last_name": "Lee",
						  "email": "blee14@imageshack.us",
						  "country": "Saudi Arabia",
						  "ip_address": "26.204.147.73"
						}, {
						  "id": 42,
						  "first_name": "Jeremy",
						  "last_name": "Miller",
						  "email": "jmiller15@blogspot.com",
						  "country": "Brazil",
						  "ip_address": "213.118.192.68"
						}, {
						  "id": 43,
						  "first_name": "Arthur",
						  "last_name": "Lawrence",
						  "email": "alawrence16@lulu.com",
						  "country": "Portugal",
						  "ip_address": "90.111.185.109"
						}, {
						  "id": 44,
						  "first_name": "Jason",
						  "last_name": "Sanchez",
						  "email": "jsanchez17@yolasite.com",
						  "country": "United States",
						  "ip_address": "78.32.243.187"
						}, {
						  "id": 45,
						  "first_name": "Kevin",
						  "last_name": "Ortiz",
						  "email": "kortiz18@spotify.com",
						  "country": "Sweden",
						  "ip_address": "137.247.164.41"
						}, {
						  "id": 46,
						  "first_name": "Frances",
						  "last_name": "Chapman",
						  "email": "fchapman19@npr.org",
						  "country": "France",
						  "ip_address": "234.42.17.158"
						}, {
						  "id": 47,
						  "first_name": "Barbara",
						  "last_name": "Reynolds",
						  "email": "breynolds1a@paginegialle.it",
						  "country": "China",
						  "ip_address": "80.35.46.147"
						}, {
						  "id": 48,
						  "first_name": "Judy",
						  "last_name": "James",
						  "email": "jjames1b@pinterest.com",
						  "country": "South Korea",
						  "ip_address": "213.105.222.190"
						}, {
						  "id": 49,
						  "first_name": "Christina",
						  "last_name": "Gonzalez",
						  "email": "cgonzalez1c@soup.io",
						  "country": "Thailand",
						  "ip_address": "137.205.226.72"
						}, {
						  "id": 50,
						  "first_name": "Ernest",
						  "last_name": "Cunningham",
						  "email": "ecunningham1d@comsenz.com",
						  "country": "China",
						  "ip_address": "186.80.17.136"
						}, {
						  "id": 51,
						  "first_name": "Thomas",
						  "last_name": "Peterson",
						  "email": "tpeterson1e@cbc.ca",
						  "country": "China",
						  "ip_address": "44.50.207.254"
						}, {
						  "id": 52,
						  "first_name": "Carol",
						  "last_name": "Medina",
						  "email": "cmedina1f@webnode.com",
						  "country": "Sweden",
						  "ip_address": "141.46.60.99"
						}, {
						  "id": 53,
						  "first_name": "Beverly",
						  "last_name": "Banks",
						  "email": "bbanks1g@clickbank.net",
						  "country": "Croatia",
						  "ip_address": "16.218.208.76"
						}, {
						  "id": 54,
						  "first_name": "Donna",
						  "last_name": "Torres",
						  "email": "dtorres1h@istockphoto.com",
						  "country": "China",
						  "ip_address": "218.172.143.188"
						}, {
						  "id": 55,
						  "first_name": "Victor",
						  "last_name": "Howell",
						  "email": "vhowell1i@dailymail.co.uk",
						  "country": "Poland",
						  "ip_address": "243.214.48.101"
						}, {
						  "id": 56,
						  "first_name": "Roger",
						  "last_name": "Jordan",
						  "email": "rjordan1j@blogspot.com",
						  "country": "Ukraine",
						  "ip_address": "150.121.124.48"
						}, {
						  "id": 57,
						  "first_name": "Mary",
						  "last_name": "Martinez",
						  "email": "mmartinez1k@japanpost.jp",
						  "country": "Japan",
						  "ip_address": "122.74.169.78"
						}, {
						  "id": 58,
						  "first_name": "Clarence",
						  "last_name": "Ford",
						  "email": "cford1l@sphinn.com",
						  "country": "Armenia",
						  "ip_address": "30.199.217.141"
						}, {
						  "id": 59,
						  "first_name": "Kathryn",
						  "last_name": "Reynolds",
						  "email": "kreynolds1m@technorati.com",
						  "country": "Portugal",
						  "ip_address": "129.248.126.126"
						}, {
						  "id": 60,
						  "first_name": "Scott",
						  "last_name": "Dixon",
						  "email": "sdixon1n@imdb.com",
						  "country": "China",
						  "ip_address": "109.76.251.23"
						}, {
						  "id": 61,
						  "first_name": "Rachel",
						  "last_name": "Duncan",
						  "email": "rduncan1o@discuz.net",
						  "country": "China",
						  "ip_address": "18.103.64.84"
						}, {
						  "id": 62,
						  "first_name": "Christina",
						  "last_name": "Ross",
						  "email": "cross1p@smh.com.au",
						  "country": "Croatia",
						  "ip_address": "170.246.112.175"
						}, {
						  "id": 63,
						  "first_name": "Ernest",
						  "last_name": "Castillo",
						  "email": "ecastillo1q@comcast.net",
						  "country": "Haiti",
						  "ip_address": "191.54.172.222"
						}, {
						  "id": 64,
						  "first_name": "Terry",
						  "last_name": "Phillips",
						  "email": "tphillips1r@amazon.co.uk",
						  "country": "China",
						  "ip_address": "33.173.76.236"
						}, {
						  "id": 65,
						  "first_name": "Heather",
						  "last_name": "Washington",
						  "email": "hwashington1s@independent.co.uk",
						  "country": "Japan",
						  "ip_address": "198.12.51.237"
						}, {
						  "id": 66,
						  "first_name": "Brenda",
						  "last_name": "Jackson",
						  "email": "bjackson1t@flavors.me",
						  "country": "Portugal",
						  "ip_address": "206.180.204.147"
						}, {
						  "id": 67,
						  "first_name": "Jesse",
						  "last_name": "Stevens",
						  "email": "jstevens1u@amazon.co.uk",
						  "country": "France",
						  "ip_address": "230.237.126.135"
						}, {
						  "id": 68,
						  "first_name": "Julie",
						  "last_name": "Reynolds",
						  "email": "jreynolds1v@etsy.com",
						  "country": "France",
						  "ip_address": "209.218.161.67"
						}, {
						  "id": 69,
						  "first_name": "Frank",
						  "last_name": "Murphy",
						  "email": "fmurphy1w@dmoz.org",
						  "country": "Peru",
						  "ip_address": "26.42.70.192"
						}, {
						  "id": 70,
						  "first_name": "Beverly",
						  "last_name": "Baker",
						  "email": "bbaker1x@intel.com",
						  "country": "Finland",
						  "ip_address": "13.92.34.204"
						}, {
						  "id": 71,
						  "first_name": "Beverly",
						  "last_name": "Rogers",
						  "email": "brogers1y@businesswire.com",
						  "country": "Slovenia",
						  "ip_address": "73.64.9.29"
						}, {
						  "id": 72,
						  "first_name": "Harry",
						  "last_name": "Howard",
						  "email": "hhoward1z@themeforest.net",
						  "country": "Morocco",
						  "ip_address": "40.54.49.164"
						}, {
						  "id": 73,
						  "first_name": "Ernest",
						  "last_name": "Hart",
						  "email": "ehart20@ihg.com",
						  "country": "Switzerland",
						  "ip_address": "245.239.218.139"
						}, {
						  "id": 74,
						  "first_name": "George",
						  "last_name": "Hill",
						  "email": "ghill21@google.com.au",
						  "country": "China",
						  "ip_address": "155.64.49.216"
						}, {
						  "id": 75,
						  "first_name": "Paula",
						  "last_name": "Morales",
						  "email": "pmorales22@reddit.com",
						  "country": "China",
						  "ip_address": "142.83.219.34"
						}, {
						  "id": 76,
						  "first_name": "Joseph",
						  "last_name": "Bowman",
						  "email": "jbowman23@msn.com",
						  "country": "Mongolia",
						  "ip_address": "121.180.225.222"
						}, {
						  "id": 77,
						  "first_name": "Jean",
						  "last_name": "Gray",
						  "email": "jgray24@taobao.com",
						  "country": "China",
						  "ip_address": "100.43.161.70"
						}, {
						  "id": 78,
						  "first_name": "Janice",
						  "last_name": "Murray",
						  "email": "jmurray25@mashable.com",
						  "country": "Sweden",
						  "ip_address": "165.232.139.203"
						}, {
						  "id": 79,
						  "first_name": "Jason",
						  "last_name": "Gibson",
						  "email": "jgibson26@mozilla.org",
						  "country": "Nepal",
						  "ip_address": "215.176.243.158"
						}, {
						  "id": 80,
						  "first_name": "Debra",
						  "last_name": "Kelley",
						  "email": "dkelley27@oaic.gov.au",
						  "country": "Indonesia",
						  "ip_address": "195.30.98.39"
						}, {
						  "id": 81,
						  "first_name": "Steve",
						  "last_name": "Morgan",
						  "email": "smorgan28@patch.com",
						  "country": "Bangladesh",
						  "ip_address": "87.253.164.172"
						}, {
						  "id": 82,
						  "first_name": "Timothy",
						  "last_name": "Spencer",
						  "email": "tspencer29@ameblo.jp",
						  "country": "Brazil",
						  "ip_address": "96.104.5.164"
						}, {
						  "id": 83,
						  "first_name": "Laura",
						  "last_name": "Flores",
						  "email": "lflores2a@dailymotion.com",
						  "country": "China",
						  "ip_address": "152.224.216.156"
						}, {
						  "id": 84,
						  "first_name": "Nicole",
						  "last_name": "Arnold",
						  "email": "narnold2b@friendfeed.com",
						  "country": "Syria",
						  "ip_address": "181.15.143.135"
						}, {
						  "id": 85,
						  "first_name": "Aaron",
						  "last_name": "Gordon",
						  "email": "agordon2c@spiegel.de",
						  "country": "Israel",
						  "ip_address": "79.82.237.20"
						}, {
						  "id": 86,
						  "first_name": "Walter",
						  "last_name": "Cunningham",
						  "email": "wcunningham2d@cyberchimps.com",
						  "country": "Japan",
						  "ip_address": "18.224.5.31"
						}, {
						  "id": 87,
						  "first_name": "Carl",
						  "last_name": "Evans",
						  "email": "cevans2e@printfriendly.com",
						  "country": "China",
						  "ip_address": "123.182.202.132"
						}, {
						  "id": 88,
						  "first_name": "Richard",
						  "last_name": "Flores",
						  "email": "rflores2f@cisco.com",
						  "country": "Ireland",
						  "ip_address": "202.27.50.116"
						}, {
						  "id": 89,
						  "first_name": "Michael",
						  "last_name": "Chapman",
						  "email": "mchapman2g@studiopress.com",
						  "country": "Philippines",
						  "ip_address": "38.222.255.211"
						}, {
						  "id": 90,
						  "first_name": "Ruby",
						  "last_name": "Johnston",
						  "email": "rjohnston2h@newsvine.com",
						  "country": "Philippines",
						  "ip_address": "26.239.236.197"
						}, {
						  "id": 91,
						  "first_name": "Phyllis",
						  "last_name": "Harrison",
						  "email": "pharrison2i@weibo.com",
						  "country": "Nauru",
						  "ip_address": "117.215.203.251"
						}, {
						  "id": 92,
						  "first_name": "Lori",
						  "last_name": "Lawrence",
						  "email": "llawrence2j@hatena.ne.jp",
						  "country": "Brazil",
						  "ip_address": "39.224.136.227"
						}, {
						  "id": 93,
						  "first_name": "Brandon",
						  "last_name": "Henry",
						  "email": "bhenry2k@gmpg.org",
						  "country": "Tunisia",
						  "ip_address": "140.96.162.162"
						}, {
						  "id": 94,
						  "first_name": "Harry",
						  "last_name": "Miller",
						  "email": "hmiller2l@uol.com.br",
						  "country": "Norway",
						  "ip_address": "252.43.213.93"
						}, {
						  "id": 95,
						  "first_name": "Frank",
						  "last_name": "Woods",
						  "email": "fwoods2m@oracle.com",
						  "country": "China",
						  "ip_address": "165.72.88.252"
						}, {
						  "id": 96,
						  "first_name": "Sara",
						  "last_name": "Chapman",
						  "email": "schapman2n@mayoclinic.com",
						  "country": "China",
						  "ip_address": "134.131.93.38"
						}, {
						  "id": 97,
						  "first_name": "Maria",
						  "last_name": "Berry",
						  "email": "mberry2o@etsy.com",
						  "country": "China",
						  "ip_address": "68.223.122.140"
						}, {
						  "id": 98,
						  "first_name": "Robert",
						  "last_name": "Young",
						  "email": "ryoung2p@shop-pro.jp",
						  "country": "Sweden",
						  "ip_address": "9.156.127.201"
						}, {
						  "id": 99,
						  "first_name": "Martha",
						  "last_name": "Morales",
						  "email": "mmorales2q@toplist.cz",
						  "country": "China",
						  "ip_address": "12.243.195.84"
						}, {
						  "id": 100,
						  "first_name": "Kathryn",
						  "last_name": "Fowler",
						  "email": "kfowler2r@salon.com",
						  "country": "Egypt",
						  "ip_address": "242.149.86.123"
						}
			];
			/*
			$scope.tableParams = new ngTableParams({
                page: 1,
                count: 10
            }, {
                total: $scope.users.length, 
                getData: function ($defer, params) {
                    $scope.data = params.sorting() ? $filter('orderBy')($scope.users, params.orderBy()) : $scope.users;
			        $scope.data = params.filter() ? $filter('filter')($scope.data, params.filter()) : $scope.data;
                    $scope.data = $scope.users.slice((params.page() - 1) * params.count(), params.page() * params.count());
                    $defer.resolve($scope.data);
                }
            });
            */
			
			$scope.tableParams = new ngTableParams({
			    page: 1,
			    count: 10
			}, {
			    //counts: [],
			    total: $scope.users.length,
			    getData: function ($defer, params) {
			        $scope.data = params.sorting() ? $filter('orderBy')($scope.users, params.orderBy()) : $scope.users;
			    	$scope.data = params.filter() ? $filter('filter')($scope.data, params.filter()) : $scope.data;
			        //$scope.data = $scope.users.slice((params.page() - 1) * params.count(), params.page() * params.count());
			        $scope.data = $scope.data.slice((params.page() - 1) * params.count(), params.page() * params.count());
			        $defer.resolve($scope.data);
			    }
			});
			
			$scope.getMoreData = function () {
				
			    //$scope.data = $scope.users.slice((params.page() - 1) * params.count(), params.page() * params.count());
			    $scope.data = $scope.users.slice(0, $scope.data.length + 10);
			}

        });